---
ID: "8f8cf0c1-7ea9-4c18-b9d8-b143083b965e"
Parent: "4f5919bd-5b93-4d02-bad1-5e13692c1ed8"
Template: "4f5919bd-5b93-4d02-bad1-5e13692c1ed8"
Path: /sitecore/templates/Feature/Blog/_Post/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211108T155640Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "de6bbf4b-1b59-45fa-8e19-f37f64a7b33f"
      Hint: Title
      Value: $name
