---
ID: "0744d638-0a5e-4bdc-866e-642e10d75966"
Parent: "d3d6ee0b-74df-4aee-86e9-35beeaf5ec5d"
Template: "d3d6ee0b-74df-4aee-86e9-35beeaf5ec5d"
Path: /sitecore/templates/Project/BasicCompany/Page Types/News List Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{4ED48317-062F-4465-B9AF-1E636841525B}">
        <r
          id="{AF0D28F1-B659-4392-8FCF-E250DF527FA3}"
          ph="header"
          uid="{5B4893F1-86BA-4ABA-8CB3-1BD6B0D10CB0}" />
        <r
          id="{6BC8AD50-DBB9-41B6-B904-799A4F50AFF7}"
          ph="main"
          uid="{96F6D181-42BF-4725-8B5E-94A2141F9A48}" />
        <r
          id="{78BCD6B7-FB7B-4D9D-90D1-78A2C45FCF49}"
          ph="footer"
          uid="{D40CD9A3-CC19-4772-AA17-191F399340C9}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211101T111624Z
    - ID: "32cff90d-4fdf-4402-a364-21199e88753d"
      Hint: Navigation Title
      Value: News
